import 'package:get/get.dart';

class MyLocal implements Translations{
  @override

  Map<String, Map<String, String>> get keys => {
    "en_US" :{
      "email" : "Email",
      "find_your_doctor" : "Find Your Doctor",
      "contant" : "Lorem ipsum dolor sit amet consectetur. Quisque lorem amet consectetur cursus enim amet a magna. Laoreet lorem ac sed imperdiet turpis. Quis in sagittis orci ultricies malesuada ac mi. Rhoncus adipiscing sagittis ligula convallis amet est pharetra amet etiam.",
      "skip": "SKIP",
      "start" : "Start",
      "please_enter_your_email" : "Please enter your email address",
      "password" : "Password",
      "please_enter_your_password" : "Please enter your password",
      "forgot_password" : "Forgot password?",
      "login" : "SIGN IN",
      "or_sign_in_with" : "or sign in with",
      "dont_have_account" : "Don’t have account?",
      "sign_up" : "SIGN UP",
      "forgotten_password": "Forgot password",
      "please_enter_your_email_address" : "Please enter your email address",
      "and_we_will_send_you_an_otpcode" : "and we will send you an OTP code to verify it first…",
      "reset_your_password" : "Reset your password",
      "otp_verification" : "OTP Verification ",
      "get_your_code" : "Get Your Code",
      "please_enter_the_5digit_code" : "Please enter the 5 digit code that",
      "sent_to_your_registered_email" : "sent to your Registered email address.",
      "didnt_receive_the_code" : "Didn't receive the code? ",
      "resend_in_60sec" : "Resend in 60sec",
      "Verify" : "Verify",
      "please_enter_new_password_redirect_you" : "Please enter your new password. We will redirect you ",
      "to_the_login_page_after_updating_your_password" : "to the login page after updating your password.",
      "new_password" : "New Password",
      "please_enter_your_new_password" : "Please enter your new password",
      "confirm_password" : "Confirm Password",
      "please_confirm_your_new_password" : "Please confirm your new password ",
      "update_password" : "Update password",
      "test_screen" : "Test Screen",
      "welcom" : "welcom"
    },
    "ar_SA" :{
      "email" : "البريد الالكتروني",
      "find_your_doctor" : "ابحث عن طبيبك",
      "contant" : "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص ، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق.إذا كنت تحتاج إلى عدد أكبر من الفقرات يتيح لك مولد النص العربى زيادة عدد الفقرات كما تريد، النص لن يبدو مقسما ولا يحوي أخطاء لغوية، مولد النص العربى مفيد لمصممي المواقع على وجه الخصوص، حيث يحتاج العميل فى كثير من الأحيان أن يطلع على صورة حقيقية لتصميم الموقع.",
      "skip": "تخطي",
      "start" : "إبدأ",
      "please_enter_your_email" : "قم بإدخال البريد الالكتروني",
      "password" : "كلمة السر",
      "please_enter_your_password" : "قم بإدخال كلمة السر",
      "forgot_password" : "هل نسيت كلمة السر؟ ",
      "login" : "تسجيل الدخول",
      "or_sign_in_with" : "او قم بتسجيل الدخول بالطرق الاتية ",
      "dont_have_account" : "ليس لديك حساب؟",
      "sign_up" : "سجل الأن",
      "forgotten_password": "نسيت كلمة السر" ,
      "please_enter_your_email_address" :" قم بإدخال بريدك الالكتروني سوف نقوم بأرسال كود",
      "and_we_will_send_you_an_otpcode" : " .مكون من 5 اراقم لأعادة ضبط كلمة السر الخاصة بك",
      "reset_your_password" : "اعد ضبط كلمه السر",
      "otp_verification" : "كود التأكيد",
      "get_your_code" : "احصل علي الكود الخاص بك",
      "please_enter_the_5digit_code" : "قم بإدخال الكود المكون من 5 ارقام الذي",
      "sent_to_your_registered_email" : " ارساله الي بريدك الالكتروني",
      "didnt_receive_the_code" : "لم تحصل علي الكود؟",
      "resend_in_60sec" :" اعد الارسال خلال 60 ثانية",
      "Verify" :"تأكيد",
      "please_enter_new_password_redirect_you":"قم بإدخال كلمة السر الجديدة الخاصة بحسابك وسوف",
      "to_the_login_page_after_updating_your_password" : " نقوم بتحويلك الي صفحة تسجيل الدخول تلقائياً.",
      "new_password" : "كلمة السر الجديدة",
      "please_enter_your_new_password" : "قم بإدخال كلمة السر الجديدة",
      "confirm_password" : "التأكيد علي كلمة السر ",
      "please_confirm_your_new_password" : "قم بالتأكيد علي كلمة السر الجديدة ",
      "update_password" : "تحديث كلمة السر",
      "test_screen" : "اختبارررررر",
      "welcom" : "مرحباااا"
    }
  };

}