// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf4WCob0Yk2zd-KxRb3zEaELK1aOTg2kA',
    appId: '1:772410507639:android:1312b71e793d7f89372172',
    messagingSenderId: '772410507639',
    projectId: 'service-provider-app-flutter',
    storageBucket: 'service-provider-app-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvb12sbs_Fbmi3CkiRzUgZni_eg6AdVp8',
    appId: '1:772410507639:ios:c92bfba8f4996e50372172',
    messagingSenderId: '772410507639',
    projectId: 'service-provider-app-flutter',
    storageBucket: 'service-provider-app-flutter.appspot.com',
    androidClientId: '772410507639-mo93b830qkrfd03d00t22250lkpu3u9r.apps.googleusercontent.com',
    iosClientId: '772410507639-077d9aq0he522crq3an6hia245e785ug.apps.googleusercontent.com',
    iosBundleId: 'com.salamat.salamatApp',
  );
}
